options:
  iburst_pools:
    type: string
    default: "0.ubuntu.pool.ntp.org,1.ubuntu.pool.ntp.org,2.ubuntu.pool.ntp.org,3.ubuntu.pool.ntp.org"
    description: |
      Comma-separated list of servers to add as iburst:
      0.ubuntu.pool.ntp.org,1.ubuntu.pool.ntp.org
  iburst_servers:
    type: string
    default: ""
    description: |
      Comma-separated list of servers to add as iburst:
      ntp.ubuntu.com,localhost
